# Generated by Django 2.2.4 on 2019-09-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'CUSTOMER'), (1, 'OWNER')], default=0),
        ),
    ]
