# Generated by Django 2.2.4 on 2019-10-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_ref', models.CharField(max_length=30)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_freezed', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_owner', to='users.Profile')),
                ('vehicles', models.ManyToManyField(related_name='fleet_vehicle', to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('is_purchased', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_fleet', to='fleet.Fleet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_payer', to='users.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
