# Generated by Django 2.2.4 on 2019-09-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0005_vehicle_booked_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_ref', models.CharField(max_length=30)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('vehicles', models.ManyToManyField(to='vehicle.Vehicle')),
            ],
        ),
    ]
