# Generated by Django 2.2.4 on 2019-09-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190924_0034'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_owner', to='users.Profile'),
        ),
    ]
