# Generated by Django 2.2.4 on 2019-09-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20190924_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_owner', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='vehicles',
            field=models.ManyToManyField(related_name='fleet_vehicle', to='vehicle.Vehicle'),
        ),
    ]
