# Generated by Django 2.2.4 on 2019-10-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_auto_20190930_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_owner', to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
