# Generated by Django 2.2.4 on 2019-10-03 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20191002_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_owner', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_payer', to='users.Profile'),
        ),
    ]
