version: '3'
volumes: 
    pgdata:
    static_files:

services: 
    web:
        build: 
            context: .
            dockerfile: docker/prod/python/Dockerfile
        volumes: 
            - ./app:/app
            - static_files:/static_files
        env_file:
            - ./.env.prod
        expose:
            - 8000 
        command: gunicorn -w 4 config.wsgi -b 0.0.0.0:8000
        depends_on:
            - postgres

    postgres:
        image: postgres
        restart: always
        volumes: 
            - pgdata:/var/lib/postgresql/data
        env_file:
            - ./.env.prod.db
        ports: 
            - 5432:5432
            
    nginx:
        build: 
            context: .
            dockerfile: docker/prod/nginx/Dockerfile
        volumes:
            - static_files:/static_files
        ports:
            - 80:80
        depends_on:
            - web
