version: '3'
volumes: 
    pgdata:
    static_files:

services: 
    web:
        build: 
            context: .
            dockerfile: docker/prod/python/Dockerfile
        volumes: 
            - ./app:/app
            - static_files:/static_files
        # ports: 
        #     - 8000:8000
        expose:
            - 8000 
        command: gunicorn -w 4 config.wsgi -b 0.0.0.0:8000
    postgres:
        image: postgres
        restart: always
        volumes: 
            - pgdata:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: bch
            POSTGRES_DB: bch_db
            POSTGRES_PASSOWRD: bch123
            POSTGRES_HOST_AUTH_METHOD: trust
        ports: 
            - 5432:5432
    nginx:
        build: 
            context: .
            dockerfile: docker/prod/nginx/Dockerfile
        volumes:
            - static_files:/static_files
        ports:
            - 80:80
