# Generated by Django 2.2.4 on 2019-09-18 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('model_year', models.DateField(blank=True, null=True)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.IntegerField(choices=[(0, 'Small Car'), (1, 'Medium Car'), (2, 'Large Car'), (3, 'Van')], default=0)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('rent_per_month', models.PositiveIntegerField(default=2000)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('is_freezed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_hired', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default_vehicle.png', upload_to=vehicle.models.photo_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicel_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vehicle_type'],
            },
        ),
    ]
