# Generated by Django 2.2.4 on 2019-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='rent_per_month',
            new_name='rent',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Audi'), (2, 'BMW'), (3, 'Chevrolet'), (4, 'Ford'), (5, 'Honda'), (6, 'Hyundai'), (7, 'Jeep'), (8, 'Kia'), (9, 'Lexus'), (10, 'Mazda'), (11, 'Mercedes-Benz'), (12, 'Mitsubishi'), (13, 'Nissan'), (14, 'Renault'), (15, 'Suzuki'), (16, 'Subaru'), (17, 'Tata'), (18, 'Toyota'), (19, 'VolksWagen'), (20, 'Volvo')], default=0),
        ),
    ]
