# Generated by Django 2.2.4 on 2019-10-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-is_approved', '-added_on']},
        ),
    ]
