# Generated by Django 2.2.4 on 2019-09-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_is_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-is_approved']},
        ),
    ]
