# Generated by Django 2.2.4 on 2019-09-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190924_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='booked_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
