# Generated by Django 2.2.4 on 2019-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
