# Generated by Django 2.2.4 on 2019-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicle_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'Van')], default=0),
        ),
    ]
