# Generated by Django 2.2.4 on 2019-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_vehicles',
            field=models.ManyToManyField(related_name='fleet_vehicles', to='vehicle.Vehicle'),
        ),
    ]
