# Generated by Django 2.2.4 on 2019-09-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0002_auto_20190903_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='fleet_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
