# Generated by Django 2.2.4 on 2019-09-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0003_fleet_fleet_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
