# Generated by Django 2.2.4 on 2019-09-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0004_fleet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='slug',
        ),
    ]
