# Generated by Django 2.2.4 on 2019-10-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted_date', '-is_approved']},
        ),
    ]
