# Generated by Django 2.2.4 on 2019-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.IntegerField(choices=[(0, 'Others'), (1, 'Vehicle'), (2, 'Service')], default=0),
        ),
    ]
