# Generated by Django 3.0 on 2019-12-12 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_auto_20191212_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepics',
            name='user',
        ),
        migrations.AddField(
            model_name='profilepics',
            name='user',
            field=models.ManyToManyField(related_name='profile_pics', to=settings.AUTH_USER_MODEL),
        ),
    ]
