# Generated by Django 3.0 on 2019-12-12 12:58

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_auto_20191212_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='ProPic.png', upload_to=CoreApp.models.photo_path),
        ),
    ]
