# Generated by Django 3.0 on 2019-12-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0004_auto_20191217_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepics',
            name='booked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepics',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclepics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_pic_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
