# Generated by Django 3.0 on 2019-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_auto_20191217_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepics',
            name='user',
        ),
    ]
