# Generated by Django 3.0 on 2019-12-12 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_blog_blogtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtopic',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_topic_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogtopic',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_topic_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
