# Generated by Django 3.0 on 2019-12-17 16:51

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0006_remove_vehiclepics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepics',
            name='image',
            field=models.ImageField(default='ProPic.png', upload_to=CoreApp.models.vehicle_photo_path),
        ),
    ]
