# Generated by Django 3.0 on 2019-12-12 14:55

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0006_auto_20191212_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=CoreApp.models.photo_path),
        ),
    ]
