# Generated by Django 3.0 on 2019-12-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0007_auto_20191217_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_ref', models.CharField(max_length=50)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_freezed', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fleet_owner', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ManyToManyField(related_name='fleet_vehicle', to='CoreApp.Vehicle')),
            ],
        ),
    ]
