# Generated by Django 3.0 on 2019-12-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0008_auto_20191212_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
    ]
