# Generated by Django 3.0 on 2019-12-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0008_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_ref',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
