# Generated by Django 3.0 on 2019-12-12 15:03

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0009_auto_20191212_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepics',
            name='image',
            field=models.ImageField(default='ProPic.png', upload_to=CoreApp.models.blog_photo_path),
        ),
    ]
