# Generated by Django 3.0 on 2019-12-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0009_auto_20191220_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepics',
            name='booked_date',
        ),
    ]
