# Generated by Django 3.0 on 2019-12-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0010_remove_vehiclepics_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='booked_date',
        ),
    ]
