# Generated by Django 3.0 on 2019-12-12 15:04

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0010_auto_20191212_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=CoreApp.models.blog_photo_path),
        ),
        migrations.AlterField(
            model_name='profilepics',
            name='image',
            field=models.ImageField(default='ProPic.png', upload_to=CoreApp.models.photo_path),
        ),
    ]
