# Generated by Django 3.0 on 2019-12-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0011_auto_20191212_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtopic',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
