# Generated by Django 3.0 on 2019-12-12 20:33

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0012_auto_20191212_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default_blog.png', null=True, upload_to=CoreApp.models.blog_photo_path),
        ),
    ]
