# Generated by Django 3.0 on 2019-12-12 20:34

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0013_auto_20191213_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=CoreApp.models.blog_photo_path),
        ),
    ]
