# Generated by Django 3.0 on 2019-12-13 12:07

import CoreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0014_auto_20191213_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog.png', null=True, upload_to=CoreApp.models.blog_photo_path),
        ),
    ]
