# Generated by Django 3.0 on 2019-12-13 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0015_auto_20191213_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
