# Generated by Django 3.0 on 2019-12-13 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0016_blog_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogtopic',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_blog', to='CoreApp.Blog')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoreApp.Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Blog_commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
