# Generated by Django 3.0 on 2019-12-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0019_auto_20191214_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
