# Generated by Django 3.0 on 2019-12-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0020_auto_20191214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replayed_commented', to='CoreApp.Comment'),
        ),
    ]
