# Generated by Django 3.0 on 2019-12-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0022_auto_20191214_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='replaied_on',
            new_name='replied_on',
        ),
    ]
