# Generated by Django 3.0 on 2019-12-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0023_auto_20191214_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repalied_blog', to='CoreApp.Blog'),
        ),
    ]
