# Generated by Django 3.0 on 2019-12-08 09:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_defaul.png', upload_to=core.models.photo_upload),
        ),
    ]
