# Generated by Django 2.2.4 on 2019-09-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0004_auto_20190929_1844'),
        ('users', '0003_auto_20190924_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_fleet', to='fleet.Fleet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_payer', to='users.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
