# Generated by Django 2.2.4 on 2019-09-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleets', '0006_auto_20190908_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_fleet', to='fleets.Fleet')),
            ],
        ),
    ]
