# Generated by Django 2.2.4 on 2019-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetpayment',
            name='account_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fleetpayment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='fleetpayment',
            name='payment_medium',
            field=models.IntegerField(choices=[(0, 'Direct Payment'), (1, 'Nagad App-pay'), (2, 'Bank Transection'), (3, 'VISA Card Payment'), (4, 'MASTERCARD Payment'), (5, 'AMERICAN EXPRESS Payment')], default=0),
        ),
        migrations.AddField(
            model_name='fleetpayment',
            name='transection_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
