# Generated by Django 2.2.4 on 2019-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190912_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetpayment',
            name='transection_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
